### PR TITLE
Update restaurants.yml

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by cfouant** [comment]
ACK

**Comment by jlsherrill** [comment]
I'm pretty sure this PR is illegal within the city limits of raleigh!

**Comment by blomquisg** [comment]
Wow, why the hatred for Raleigh Times?  I agree with @jlsherrill, you're likely to get mugged if you remove that from the list.  Of course, you're likely to get mugged on your way there, too...

**Comment by jeremycline** [comment]
Looks good to me. ACK.

**Comment by cfouant** [comment]
you should add Jose & Sons btw

**Comment by komidore64** [comment]
@cfouant THAT IS OUTSIDE THE SCOPE OF THIS PULL-REQUEST

**Comment by jlsherrill** [comment]
There are a ton of restaurants that could be added: hot dog place, plaza cafe, rye

Who wants to form a feature team?

**Comment by cfouant** [comment]
I created a pull request for joule MONTHS ago. It has yet to be merged. Maybe somebody else, I nominate @jlsherrill

**Comment by komidore64** [comment]
joule is a coffeeshop

**Comment by cfouant** [comment]
with a full menu

**Comment by komidore64** [comment]
of extremely expensive snacks

**Comment by cfouant** [comment]
PS ACK to this - I'm pretty sure everybody who ate lunch there yesterday was disappointed also

**Comment by cfouant** [comment]
(oh i already ACKed. me--)

**Pull request merged**
